packages:
  - "apps/*"
  - "packages/*"
  - "!**/node_modules/**"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  bcrypt: true
  core-js: true
  core-js-pure: true
  esbuild: true
